package enums;

public enum MaterialTypes {

	ORE, SAND, FABRIC, THREAD, MEAT, HORN, METALINGOT, FUR, PELT, SKIN, BONE, FANG, TUSK, CLAW, FEATHER, GEMSTONE, GRASS, HERB, FLOWER, MUSHROOM, WOOD, LIQUID, SCROLL, OTHER;
}
