package enums;

public enum SpecificType {

	HEAD_ARMOUR, BODY_ARMOUR, BODY_CLOTHING, ARM_ARMOUR, LEG_ARMOUR, LEGWEAR, OVERWEAR, JEWELLERY, ENSEMBLES, ORE, SAND, FABRIC, THREAD, MEAT, HORN, METALINGOT, FUR, PELT, SKIN, BONE, FANG, TUSK, CLAW, FEATHER, GEMSTONE, GRASS, HERB, FLOWER, MUSHROOM, WOOD, LIQUID, SCROLL, OTHER;

}
